-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

CREATE TABLE __DBSCHEMA__.SIBOWNER (
  ME_UUID VARCHAR(16),
  INC_UUID VARCHAR(16),
  VERSION INTEGER,
  MIGRATION_VERSION INTEGER,
  TIME_CREATED TIMESTAMP,
  ME_INFO VARCHAR(254),
  ME_STATUS VARCHAR(16)
);

CREATE TABLE __DBSCHEMA__.SIBOWNERO (
  EMPTY_COLUMN INTEGER
);

CREATE TABLE __DBSCHEMA__.SIBCLASSMAP (
  CLASSID INTEGER NOT NULL,
  URI VARCHAR2(2048) NOT NULL,
  PRIMARY KEY(CLASSID)
);

CREATE TABLE __DBSCHEMA__.SIBLISTING (
  ID INTEGER NOT NULL,
  SCHEMA_NAME VARCHAR2(10),
  TABLE_NAME VARCHAR2(10) NOT NULL,
  TABLE_TYPE CHAR(1) NOT NULL,
  PRIMARY KEY(ID)
);

CREATE TABLE __DBSCHEMA__.SIB000 (
  ID NUMBER(19) NOT NULL,
  STREAM_ID NUMBER(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME NUMBER(19),
  STRATEGY INTEGER,
  REFERENCE NUMBER(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE NUMBER(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID NUMBER(19),
  DATA_SIZE INTEGER NOT NULL,
  LONG_DATA BLOB,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER
) LOB(LONG_DATA) STORE AS (CACHE STORAGE(INITIAL 10M NEXT 10M));

CREATE INDEX __DBSCHEMA__.SIB000STREAMIX ON
__DBSCHEMA__.SIB000(STREAM_ID,SEQUENCE);

CREATE TABLE __DBSCHEMA__.SIB001 (
  ID NUMBER(19) NOT NULL,
  STREAM_ID NUMBER(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME NUMBER(19),
  STRATEGY INTEGER,
  REFERENCE NUMBER(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE NUMBER(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID NUMBER(19),
  DATA_SIZE INTEGER NOT NULL,
  LONG_DATA BLOB,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER
) LOB(LONG_DATA) STORE AS (CACHE STORAGE(INITIAL 10M NEXT 10M));

CREATE INDEX __DBSCHEMA__.SIB001STREAMIX ON
__DBSCHEMA__.SIB001(STREAM_ID,SEQUENCE);

CREATE TABLE __DBSCHEMA__.SIB002 (
  ID NUMBER(19) NOT NULL,
  STREAM_ID NUMBER(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME NUMBER(19),
  STRATEGY INTEGER,
  REFERENCE NUMBER(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE NUMBER(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID NUMBER(19),
  DATA_SIZE INTEGER NOT NULL,
  LONG_DATA BLOB,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER 
) LOB(LONG_DATA) STORE AS (CACHE STORAGE(INITIAL 10M NEXT 10M));

CREATE INDEX __DBSCHEMA__.SIB002STREAMIX ON
__DBSCHEMA__.SIB002(STREAM_ID,SEQUENCE);

CREATE TABLE __DBSCHEMA__.SIBXACTS (
  XID VARCHAR2(254) NOT NULL,
  STATE CHAR(1) NOT NULL,
  PRIMARY KEY(XID)
);

CREATE TABLE __DBSCHEMA__.SIBKEYS (
  ID VARCHAR2(50) NOT NULL,
  LAST_KEY NUMBER(19) NOT NULL,
  PRIMARY KEY(ID)
);

GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNER TO __DBUSER__;

GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNERO TO __DBUSER__;

GRANT SELECT,INSERT ON __DBSCHEMA__.SIBCLASSMAP TO __DBUSER__;

GRANT SELECT,INSERT ON __DBSCHEMA__.SIBLISTING TO __DBUSER__;

GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB000 TO __DBUSER__;

GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB001 TO __DBUSER__;

GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB002 TO __DBUSER__;

GRANT SELECT,INSERT,UPDATE,DELETE ON __DBSCHEMA__.SIBXACTS TO __DBUSER__;

GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBKEYS TO __DBUSER__;

GRANT DROP ANY TABLE TO __DBUSER__;
