-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2008 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

------------------------------------------------
SET CURRENT SCHEMA = '@WSRR_DB_SCHEMA@' ;

DROP TABLE @WSRR_DB_SCHEMA@.VERIFY ;

DROP INDEX @WSRR_DB_SCHEMA@.I_WIRE_SOURCEWID;
DROP INDEX @WSRR_DB_SCHEMA@.I_WIRE_TARGETWID;
DROP INDEX @WSRR_DB_SCHEMA@.I_WIRE_WIDGETINSTA;
DROP INDEX @WSRR_DB_SCHEMA@.I_WDGT_WR_WIDGETIN;
DROP INDEX @WSRR_DB_SCHEMA@.I_WDGT_WR_ELEMENT;
DROP INDEX @WSRR_DB_SCHEMA@.I_WDGTTNC_PAGE;
DROP INDEX @WSRR_DB_SCHEMA@.I_STT_ITM_VALUEDAT;
DROP INDEX @WSRR_DB_SCHEMA@.I_STT_ITM_STATESET;
DROP INDEX @WSRR_DB_SCHEMA@.I_STT_ITM_LOCALIZE;
DROP INDEX @WSRR_DB_SCHEMA@.I_STATESET;
DROP INDEX @WSRR_DB_SCHEMA@.CRE_LARGE_CDATA_DATA_IDX ;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_LARGE_CDATA_DATA ;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_LARGE_CDATA;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_PAGE;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_STATE_ITEM;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_STATE_SET;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_WIDGET_INSTANCE_CRE_WIRE;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_WIDGET_INSTANCE;
DROP TABLE @WSRR_DB_SCHEMA@.CRE_WIRE;
DROP VIEW  @WSRR_DB_SCHEMA@.USERVIEWPERM_VW;
DROP VIEW  @WSRR_DB_SCHEMA@.DEFAULTPERM_VW;
DROP INDEX @WSRR_DB_SCHEMA@.UIUSERSTORAGE_USERDATA_IDX ;
DROP TABLE @WSRR_DB_SCHEMA@.UIUSERSTORAGE_USERDATA ;
DROP TABLE @WSRR_DB_SCHEMA@.UIUSERSTORAGE;
DROP TABLE @WSRR_DB_SCHEMA@.UIUSER;
DROP TABLE @WSRR_DB_SCHEMA@.USERVIEWPERM;
DROP TABLE @WSRR_DB_SCHEMA@.DEFAULTPERM;
DROP TABLE @WSRR_DB_SCHEMA@.UISTATUSFLAG;
DROP TABLESPACE @WSRR_DB_NAME@.UISTORAG ;
DROP TABLESPACE @WSRR_DB_NAME@.CRELOB ;
DROP TABLESPACE @WSRR_DB_NAME@.UITS ;


DROP TABLE @WSRR_DB_SCHEMA@.UPGRADECOMPONENTS ;
DROP TABLESPACE @WSRR_DB_NAME@.UPGRADE5 ;
DROP TABLE @WSRR_DB_SCHEMA@.UPGRADEOBJECTSTATUS ;
DROP TABLESPACE @WSRR_DB_NAME@.UPGRADE4 ;
DROP TABLE @WSRR_DB_SCHEMA@.UPGRADEOBJECTHISTORY ;
DROP TABLESPACE @WSRR_DB_NAME@.UPGRADE3 ;
DROP TABLE @WSRR_DB_SCHEMA@.UPGRADEEXCEPTIONS ;
DROP TABLESPACE @WSRR_DB_NAME@.UPGRADE2 ;
DROP TABLE @WSRR_DB_SCHEMA@.UPGRADESTATUSRECORD ;
DROP TABLESPACE @WSRR_DB_NAME@.UPGRADE1 ;

DROP INDEX @WSRR_DB_SCHEMA@.WSRRLMPR_IDX1 ;
DROP TABLE @WSRR_DB_SCHEMA@.WSRRLMPR ;
DROP TABLE @WSRR_DB_SCHEMA@.WSRRLMGR ;
DROP TABLE @WSRR_DB_SCHEMA@.WSRRTREG ;
DROP INDEX @WSRR_DB_SCHEMA@.WSRRTASK_IDX2 ;
DROP INDEX @WSRR_DB_SCHEMA@.WSRRTASK_IDX1 ;
DROP TABLE @WSRR_DB_SCHEMA@.WSRRTASK ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRSHD1 ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRSHD ;

DROP TABLESPACE @WSRR_DB_NAME@.BLUPGTS1 ;
DROP TABLESPACE @WSRR_DB_NAME@.BLUPGTS2 ;
DROP TABLESPACE @WSRR_DB_NAME@.BLUPGTS3 ;

DROP TABLE @WSRR_DB_SCHEMA@.SR_WMB_POLICY ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL7 ;
DROP TABLE @WSRR_DB_SCHEMA@.SR_VALDTRPOLICY ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL6 ;
DROP TABLE @WSRR_DB_SCHEMA@.SR_ENTITYACTION ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL5 ;
DROP INDEX @WSRR_DB_SCHEMA@.SR_ASSOCIATED_IDX ;
DROP TABLE @WSRR_DB_SCHEMA@.SR_ASSOCIATED ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL4 ;
DROP TABLE @WSRR_DB_SCHEMA@.SR_ASSERTION ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL3 ;

DROP TABLE @WSRR_DB_SCHEMA@.SR_ANALYTICSAUX ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL2 ;
DROP INDEX @WSRR_DB_SCHEMA@.SR_ANALYTICS_VER_IDX ;
DROP TABLE @WSRR_DB_SCHEMA@.SR_ANALYTICS ;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRPOL1 ;


COMMIT ;
