-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

-----------------------------------------------------------------------
-- WebSphere Service Registry and Repository
-- Create the WSRR Service Integration Bus Tables
-----------------------------------------------------------------------
SET CURRENT SCHEMA = '@SIB_DB_SCHEMA@' ;

-----------------------------------------------------------------------
-- DDL Statements for table SIBOWNER
-----------------------------------------------------------------------
CREATE TABLESPACE OWNERTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 3200
  SECQTY 320
  ERASE NO
  PCTFREE 0
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE TABLE
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBOWNER (
  ME_UUID VARCHAR(16),
  INC_UUID VARCHAR(16),
  VERSION INTEGER,
  MIGRATION_VERSION INTEGER,
  ME_LUTS TIMESTAMP,
  ME_INFO VARCHAR(254),
  ME_STATUS VARCHAR(16))
  IN @SIB_DB_NAME@.OWNERTS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIBOWNER
  ON @SIB_DB_SCHEMA@.SIBOWNER(
  ME_UUID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 200
  SECQTY 20 ;

-----------------------------------------------------------------------
-- DDL Statements for table SIBOWNERO
-----------------------------------------------------------------------
CREATE TABLESPACE OWNEROTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 3200
  SECQTY 320
  ERASE NO
  PCTFREE 0
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE TABLE
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBOWNERO (
  EMPTY_COLUMN INTEGER)
  IN @SIB_DB_NAME@.OWNEROTS ;

-----------------------------------------------------------------------
-- DDL Statements for table SIBCLASSMAP
-----------------------------------------------------------------------
CREATE TABLESPACE MAPTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 3200
  SECQTY 320
  ERASE NO
  PCTFREE 10
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ANY
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBCLASSMAP (
  CLASSID INTEGER NOT NULL,
  URI VARCHAR(2048) NOT NULL,
  PRIMARY KEY(CLASSID))
  IN @SIB_DB_NAME@.MAPTS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIBCLASSMAP
  ON @SIB_DB_SCHEMA@.SIBCLASSMAP(CLASSID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 200
  SECQTY 20 ;

-----------------------------------------------------------------------
-- DDL Statements for table SIBLISTING
-----------------------------------------------------------------------
CREATE TABLESPACE LISTTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 3200
  SECQTY 320
  ERASE NO
  PCTFREE 0
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ANY
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBLISTING (
  ID INTEGER NOT NULL,
  SCHEMA_NAME VARCHAR(10),
  TABLE_NAME VARCHAR(10) NOT NULL,
  TABLE_TYPE CHAR(1) NOT NULL,
  PRIMARY KEY(ID))
  IN @SIB_DB_NAME@.LISTTS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIBLISTING
  ON @SIB_DB_SCHEMA@.SIBLISTING(ID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 200
  SECQTY 20 ;
  
  
-----------------------------------------------------------------------
-- DDL Statements for table SIB000
-----------------------------------------------------------------------
CREATE TABLESPACE SIB000TS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 10240
  SECQTY 1024
  ERASE NO
  PCTFREE 20
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ROW
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIB000 (
  ID DECIMAL(19) NOT NULL,
  STREAM_ID DECIMAL(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME DECIMAL(19),
  STRATEGY INTEGER,
  REFERENCE DECIMAL(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE DECIMAL(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID DECIMAL(19),
  DATA_SIZE INTEGER NOT NULL,
  DATA VARCHAR(3360) FOR BIT DATA,
  LONG_DATA BLOB(100M),
  LONG_DATA_ID ROWID GENERATED ALWAYS NOT NULL,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER)
  IN @SIB_DB_NAME@.SIB000TS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB000
  ON @SIB_DB_SCHEMA@.SIB000(ID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE LOB TABLESPACE SIB000LS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 102400
  SECQTY 10240
  BUFFERPOOL BP1
  LOCKSIZE LOB ;

CREATE AUXILIARY TABLE @SIB_DB_SCHEMA@.SIB000AUX
  IN @SIB_DB_NAME@.SIB000LS
  STORES @SIB_DB_SCHEMA@.SIB000
  COLUMN LONG_DATA ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB000AUXIX
  ON @SIB_DB_SCHEMA@.SIB000AUX
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE INDEX @SIB_DB_SCHEMA@.SIB000STREAMIX
  ON @SIB_DB_SCHEMA@.SIB000(STREAM_ID,SEQUENCE)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

-----------------------------------------------------------------------
-- DDL Statements for table SIB001
-----------------------------------------------------------------------
CREATE TABLESPACE SIB001TS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 10240
  SECQTY 1024
  ERASE NO
  PCTFREE 20
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ROW
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIB001 (
  ID DECIMAL(19) NOT NULL,
  STREAM_ID DECIMAL(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME DECIMAL(19),
  STRATEGY INTEGER,
  REFERENCE DECIMAL(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE DECIMAL(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID DECIMAL(19),
  DATA_SIZE INTEGER NOT NULL,
  DATA VARCHAR(3360) FOR BIT DATA,
  LONG_DATA BLOB(100M),
  LONG_DATA_ID ROWID GENERATED ALWAYS NOT NULL,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER)
  IN @SIB_DB_NAME@.SIB001TS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB001
  ON @SIB_DB_SCHEMA@.SIB001(
  ID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE LOB TABLESPACE SIB001LS IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 102400
  SECQTY 10240
  BUFFERPOOL BP1
  LOCKSIZE LOB ;

CREATE AUXILIARY TABLE @SIB_DB_SCHEMA@.SIB001AUX
  IN @SIB_DB_NAME@.SIB001LS
  STORES @SIB_DB_SCHEMA@.SIB001
  COLUMN LONG_DATA ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB001AUXIX
  ON @SIB_DB_SCHEMA@.SIB001AUX
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE INDEX @SIB_DB_SCHEMA@.SIB001STREAMIX
  ON @SIB_DB_SCHEMA@.SIB001(
  STREAM_ID,SEQUENCE)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

-----------------------------------------------------------------------
-- DDL Statements for table SIB002
-----------------------------------------------------------------------
CREATE TABLESPACE SIB002TS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 10240
  SECQTY 1024
  ERASE NO
  PCTFREE 20
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ROW
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIB002 (
  ID DECIMAL(19) NOT NULL,
  STREAM_ID DECIMAL(19) NOT NULL,
  TYPE CHAR(2),
  EXPIRY_TIME DECIMAL(19),
  STRATEGY INTEGER,
  REFERENCE DECIMAL(19),
  CLASS_ID INTEGER NOT NULL,
  PRIORITY INTEGER,
  SEQUENCE DECIMAL(19),
  PERMANENT_ID INTEGER,
  TEMPORARY_ID INTEGER,
  LOCK_ID DECIMAL(19),
  DATA_SIZE INTEGER NOT NULL,
  DATA VARCHAR(3360) FOR BIT DATA,
  LONG_DATA BLOB(100M),
  LONG_DATA_ID ROWID GENERATED ALWAYS NOT NULL,
  XID VARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY(ID),
  REDELIVERED_COUNT INTEGER)
  IN @SIB_DB_NAME@.SIB002TS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB002
  ON @SIB_DB_SCHEMA@.SIB002(
  ID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE LOB TABLESPACE SIB002LS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 102400
  SECQTY 10240
  BUFFERPOOL BP1
  LOCKSIZE LOB ;

CREATE AUXILIARY TABLE @SIB_DB_SCHEMA@.SIB002AUX
  IN @SIB_DB_NAME@.SIB002LS
  STORES @SIB_DB_SCHEMA@.SIB002
  COLUMN LONG_DATA ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIB002AUXIX
  ON @SIB_DB_SCHEMA@.SIB002AUX
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

CREATE INDEX @SIB_DB_SCHEMA@.SIB002STREAMIX
  ON @SIB_DB_SCHEMA@.SIB002(
  STREAM_ID,SEQUENCE)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 500
  SECQTY 50 ;

-----------------------------------------------------------------------
-- DDL Statements for table SIBXACTS
-----------------------------------------------------------------------
CREATE TABLESPACE XACTSTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 6400
  SECQTY 640
  ERASE NO
  PCTFREE 20
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ROW
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBXACTS (
  XID VARCHAR(254) NOT NULL,
  STATE CHAR(1) NOT NULL,
  PRIMARY KEY(XID))
  IN @SIB_DB_NAME@.XACTSTS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIBXACTS
  ON @SIB_DB_SCHEMA@.SIBXACTS(
  XID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 200
  SECQTY 20 ;

CREATE TABLESPACE KEYTS
  IN @SIB_DB_NAME@
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 3200
  SECQTY 320
  ERASE NO
  PCTFREE 10
  SEGSIZE 32
  BUFFERPOOL BP1
  LOCKSIZE ANY
  CLOSE NO ;

CREATE TABLE @SIB_DB_SCHEMA@.SIBKEYS (
  ID VARCHAR(50) NOT NULL,
  LAST_KEY DECIMAL(19) NOT NULL,
  PRIMARY KEY(ID))
  IN @SIB_DB_NAME@.KEYTS ;

CREATE UNIQUE INDEX @SIB_DB_SCHEMA@.SIBKEYS
  ON @SIB_DB_SCHEMA@.SIBKEYS(
  ID)
  USING
  STOGROUP @SIB_DB_STOGRP@
  PRIQTY 200
  SECQTY 20 ;

-----------------------------------------------------------------------
-- DDL Statements for grants
-----------------------------------------------------------------------
SET CURRENT RULES = 'STD' ;
 
GRANT SELECT,INSERT,UPDATE
  ON @SIB_DB_SCHEMA@.SIBOWNER
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,UPDATE
  ON @SIB_DB_SCHEMA@.SIBOWNERO
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT
  ON @SIB_DB_SCHEMA@.SIBCLASSMAP
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT
  ON @SIB_DB_SCHEMA@.SIBLISTING
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,DELETE,UPDATE
  ON @SIB_DB_SCHEMA@.SIB000
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,DELETE,UPDATE
  ON @SIB_DB_SCHEMA@.SIB001
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,DELETE,UPDATE
  ON @SIB_DB_SCHEMA@.SIB002
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,UPDATE,DELETE
  ON @SIB_DB_SCHEMA@.SIBXACTS
  TO @SIB_DB_USER@ ;

GRANT SELECT,INSERT,UPDATE
  ON @SIB_DB_SCHEMA@.SIBKEYS
  TO @SIB_DB_USER@ ;

SET CURRENT RULES = 'DB2' ;
