-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2008 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

------------------------------------------------
SET CURRENT SCHEMA = '@SIB_DB_SCHEMA@' ;

DROP TABLE @SIB_DB_SCHEMA@.SIBKEYS ;
DROP TABLESPACE @SIB_DB_NAME@.KEYTS ;

DROP TABLE @SIB_DB_SCHEMA@.SIBXACTS ;
DROP TABLESPACE @SIB_DB_NAME@.XACTSTS ;

DROP INDEX @SIB_DB_SCHEMA@.SIB002STREAMIX ;
DROP TABLE @SIB_DB_SCHEMA@.SIB002AUX ;
DROP TABLESPACE @SIB_DB_NAME@.SIB002LS ;

DROP TABLE @SIB_DB_SCHEMA@.SIB002 ;
DROP TABLESPACE @SIB_DB_NAME@.SIB002TS ;

DROP INDEX @SIB_DB_SCHEMA@.SIB001STREAMIX ;
DROP TABLE @SIB_DB_SCHEMA@.SIB001AUX ;
DROP TABLESPACE @SIB_DB_NAME@.SIB001LS ;

DROP TABLE @SIB_DB_SCHEMA@.SIB001 ;
DROP TABLESPACE @SIB_DB_NAME@.SIB001TS ;

DROP INDEX @SIB_DB_SCHEMA@.SIB000STREAMIX ;
DROP TABLE @SIB_DB_SCHEMA@.SIB000AUX ;
DROP TABLESPACE @SIB_DB_NAME@.SIB000LS ;

DROP TABLE @SIB_DB_SCHEMA@.SIB000 ;
DROP TABLESPACE @SIB_DB_NAME@.SIB000TS ;

DROP TABLE @SIB_DB_SCHEMA@.SIBLISTING ;
DROP TABLESPACE @SIB_DB_NAME@.LISTTS ;

DROP TABLE @SIB_DB_SCHEMA@.SIBCLASSMAP ;
DROP TABLESPACE @SIB_DB_NAME@.MAPTS ;

DROP TABLE @SIB_DB_SCHEMA@.SIBOWNERO ;
DROP TABLESPACE @SIB_DB_NAME@.OWNEROTS ;

DROP TABLE @SIB_DB_SCHEMA@.SIBOWNER ;
DROP TABLESPACE @SIB_DB_NAME@.OWNERTS ;

COMMIT ;
