-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

CREATE TABLE __DBSCHEMA__.SIBOWNER (
  ME_UUID VARCHAR(16),
  INC_UUID VARCHAR(16),
  VERSION INT,
  MIGRATION_VERSION INT,
  ME_LUTS datetime,
  ME_INFO VARCHAR(254),
  ME_STATUS VARCHAR(16)
);


CREATE TABLE __DBSCHEMA__.SIBOWNERO (
  EMPTY_COLUMN INT
);


CREATE TABLE __DBSCHEMA__.SIBCLASSMAP (
  CLASSID INT NOT NULL,
  URI NVARCHAR(2048) NOT NULL,
  PRIMARY KEY(CLASSID)
);


CREATE TABLE __DBSCHEMA__.SIBLISTING (
  ID INT NOT NULL,
  SCHEMA_NAME NVARCHAR(10),
  TABLE_NAME NVARCHAR(10) NOT NULL,
  TABLE_TYPE NCHAR(1) NOT NULL,
  PRIMARY KEY(ID)
);


CREATE TABLE __DBSCHEMA__.SIB000 (
  ID BIGINT NOT NULL,
  STREAM_ID BIGINT NOT NULL,
  TYPE NCHAR(2),
  EXPIRY_TIME BIGINT,
  STRATEGY INT,
  REFERENCE BIGINT,
  CLASS_ID INT NOT NULL,
  PRIORITY INT,
  SEQUENCE BIGINT,
  PERMANENT_ID INT,
  TEMPORARY_ID INT,
  LOCK_ID BIGINT,
  DATA_SIZE INT NOT NULL,
  LONG_DATA IMAGE,
  XID NVARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY NONCLUSTERED (ID),
  REDELIVERED_COUNT  INT
);


CREATE CLUSTERED INDEX SIB000STREAMIX ON __DBSCHEMA__.SIB000(STREAM_ID,SEQUENCE);


CREATE TABLE __DBSCHEMA__.SIB001 (
  ID BIGINT NOT NULL,
  STREAM_ID BIGINT NOT NULL,
  TYPE NCHAR(2),
  EXPIRY_TIME BIGINT,
  STRATEGY INT,
  REFERENCE BIGINT,
  CLASS_ID INT NOT NULL,
  PRIORITY INT,
  SEQUENCE BIGINT,
  PERMANENT_ID INT,
  TEMPORARY_ID INT,
  LOCK_ID BIGINT,
  DATA_SIZE INT NOT NULL,
  LONG_DATA IMAGE,
  XID NVARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY NONCLUSTERED (ID),
  REDELIVERED_COUNT  INT
);


CREATE CLUSTERED INDEX SIB001STREAMIX ON
__DBSCHEMA__.SIB001(STREAM_ID,SEQUENCE);


CREATE TABLE __DBSCHEMA__.SIB002 (
  ID BIGINT NOT NULL,
  STREAM_ID BIGINT NOT NULL,
  TYPE NCHAR(2),
  EXPIRY_TIME BIGINT,
  STRATEGY INT,
  REFERENCE BIGINT,
  CLASS_ID INT NOT NULL,
  PRIORITY INT,
  SEQUENCE BIGINT,
  PERMANENT_ID INT,
  TEMPORARY_ID INT,
  LOCK_ID BIGINT,
  DATA_SIZE INT NOT NULL,
  LONG_DATA IMAGE,
  XID NVARCHAR(254),
  DELETED SMALLINT,
  PRIMARY KEY NONCLUSTERED (ID),
  REDELIVERED_COUNT  INT
);


CREATE CLUSTERED INDEX SIB002STREAMIX ON
__DBSCHEMA__.SIB002(STREAM_ID,SEQUENCE);


CREATE TABLE __DBSCHEMA__.SIBXACTS (
  XID NVARCHAR(254) NOT NULL,
  STATE NCHAR(1) NOT NULL,
  PRIMARY KEY(XID)
);


CREATE TABLE __DBSCHEMA__.SIBKEYS (
  ID NVARCHAR(50) NOT NULL,
  LAST_KEY BIGINT NOT NULL,
  PRIMARY KEY(ID)
);


GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNER TO __DBUSER__;
GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNERO TO __DBUSER__;
GRANT SELECT,INSERT ON __DBSCHEMA__.SIBCLASSMAP TO __DBUSER__;
GRANT SELECT,INSERT ON __DBSCHEMA__.SIBLISTING TO __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB000 TO __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB001 TO __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB002 TO __DBUSER__;
GRANT SELECT,INSERT,UPDATE,DELETE ON __DBSCHEMA__.SIBXACTS TO __DBUSER__;
GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBKEYS TO __DBUSER__;

GO -- remove this line if running through JDBC
