-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2008 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

------------------------------------------------

DROP INDEX IDX_VALUE_LANG ON __DBSCHEMA__.OBJECT;

DROP INDEX IDX_STMT_OBJ_HASH_REL ON __DBSCHEMA__.STATEMENT;
DROP INDEX IDX_STMT_PRED_OBJ_SUBJ ON __DBSCHEMA__.STATEMENT;
DROP INDEX IDX_STMT_SUBJ_PRED_OBJ ON __DBSCHEMA__.STATEMENT;
DROP INDEX IDX_STMT_OBJ_SUBJ_PRED ON __DBSCHEMA__.STATEMENT;



DROP INDEX IDX_GSTMT_REL_SUBJ ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_REL_OBJ ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_GRAPH ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_PRED ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_PRED_OBJ_SUB ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_OBJ_SUBJ_PRED ON __DBSCHEMA__.GSTATEMENT;
DROP INDEX IDX_GSTMT_INSTANCE_ROW ON __DBSCHEMA__.GSTATEMENT;

DROP INDEX IDX_OBJ_STRING ON __DBSCHEMA__.OBJECT;
DROP INDEX IDX_PRED_URI ON __DBSCHEMA__.PREDICATE;
DROP INDEX IDX_GRAPH_URI ON __DBSCHEMA__.GRAPH;
DROP INDEX IDX_SUBJ_URI ON __DBSCHEMA__.SUBJECT;

DROP VIEW __DBSCHEMA__.SVC_STATEMENT;
DROP TABLE __DBSCHEMA__.GSTATEMENT;
DROP TABLE __DBSCHEMA__.STATEMENT;
DROP TABLE __DBSCHEMA__.GRAPH;
DROP TABLE __DBSCHEMA__.OBJECT;
DROP TABLE __DBSCHEMA__.PREDICATE;
DROP TABLE __DBSCHEMA__.SUBJECT;
DROP TABLE __DBSCHEMA__.MOD_LOCK;

GO -- remove this line if running through JDBC
