-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2008 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

------------------------------------------------
DROP VIEW __DBSCHEMA__.USERVIEWPERM_VW;
DROP VIEW __DBSCHEMA__.DEFAULTPERM_VW;
DROP INDEX UV_VIEW ON __DBSCHEMA__.USERVIEWPERM;
DROP TABLE __DBSCHEMA__.USERVIEWPERM;
DROP INDEX DEF_VIEW ON __DBSCHEMA__.DEFAULTPERM;
DROP TABLE __DBSCHEMA__.DEFAULTPERM;
DROP TABLE __DBSCHEMA__.UISTATUSFLAG;
DROP TABLE __DBSCHEMA__.UIUSER;
DROP TABLE __DBSCHEMA__.UIUSERSTORAGE;

DROP INDEX I_STT_ITM_VALUEDAT ON __DBSCHEMA__.CRE_STATE_ITEM;
DROP INDEX I_STT_ITM_STATESET ON __DBSCHEMA__.CRE_STATE_ITEM;
DROP INDEX I_STT_ITM_LOCALIZE ON __DBSCHEMA__.CRE_STATE_ITEM;
DROP TABLE __DBSCHEMA__.CRE_STATE_ITEM;
DROP TABLE __DBSCHEMA__.CRE_LARGE_CDATA;
DROP TABLE __DBSCHEMA__.VERIFY;

DROP TABLE __DBSCHEMA__.UPGRADECOMPONENTS;
DROP TABLE __DBSCHEMA__.UPGRADEOBJECTSTATUS;
DROP TABLE __DBSCHEMA__.UPGRADEOBJECTHISTORY;
DROP TABLE __DBSCHEMA__.UPGRADEEXCEPTIONS;
DROP TABLE __DBSCHEMA__.UPGRADESTATUSRECORD;

DROP INDEX WSRRLMPR_IDX1 ON __DBSCHEMA__.WSRRLMPR;
DROP TABLE __DBSCHEMA__.WSRRLMPR;
DROP TABLE __DBSCHEMA__.WSRRLMGR;
DROP TABLE __DBSCHEMA__.WSRRTREG;
DROP INDEX WSRRTASK_IDX2 ON __DBSCHEMA__.WSRRTASK;
DROP INDEX WSRRTASK_IDX1 ON __DBSCHEMA__.WSRRTASK;
DROP TABLE __DBSCHEMA__.WSRRTASK;

DROP TABLE __DBSCHEMA__.SR_WMB_POLICY;
DROP TABLE __DBSCHEMA__.SR_VALDTRPOLICY;
DROP TABLE __DBSCHEMA__.SR_ENTITYACTION;
DROP TABLE __DBSCHEMA__.SR_ASSOCIATED;
DROP TABLE __DBSCHEMA__.SR_ASSERTION;
DROP INDEX SR_ANALYTICS_VER_IDX ON __DBSCHEMA__.SR_ANALYTICS;
DROP TABLE __DBSCHEMA__.SR_ANALYTICS;

DROP INDEX I_WDGT_WR_WIDGETIN ON __DBSCHEMA__.CRE_WIDGET_INSTANCE_CRE_WIRE;
DROP INDEX I_WDGT_WR_ELEMENT ON __DBSCHEMA__.CRE_WIDGET_INSTANCE_CRE_WIRE;
DROP TABLE __DBSCHEMA__.CRE_WIDGET_INSTANCE_CRE_WIRE;

DROP INDEX I_WIRE_SOURCEWID ON __DBSCHEMA__.CRE_WIRE;
DROP INDEX I_WIRE_TARGETWID ON __DBSCHEMA__.CRE_WIRE;
DROP INDEX I_WIRE_WIDGETINSTA ON __DBSCHEMA__.CRE_WIRE;
DROP TABLE __DBSCHEMA__.CRE_WIRE;

DROP INDEX I_WDGTTNC_PAGE ON __DBSCHEMA__.CRE_WIDGET_INSTANCE;
DROP TABLE __DBSCHEMA__.CRE_WIDGET_INSTANCE;
DROP INDEX I_STATESET ON __DBSCHEMA__.CRE_STATE_SET;
DROP TABLE __DBSCHEMA__.CRE_STATE_SET;
DROP TABLE __DBSCHEMA__.CRE_PAGE;

GO -- remove this line if running through JDBC
