-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2008, 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

CREATE TABLE __DBSCHEMA__.SIBOWNER (
    ME_UUID VARCHAR(16),
    INC_UUID VARCHAR(16),
    VERSION INTEGER,
    MIGRATION_VERSION INTEGER,
    ME_LUTS TIMESTAMP,
    ME_INFO VARCHAR(254),
    ME_STATUS VARCHAR(16)
) IN USERSPACE1;

CREATE TABLE __DBSCHEMA__.SIBOWNERO (
    EMPTY_COLUMN INTEGER
) IN USERSPACE1;

CREATE TABLE __DBSCHEMA__.SIBCLASSMAP (
    CLASSID INTEGER NOT NULL,
    URI VARCHAR(2048) NOT NULL,
    PRIMARY KEY(CLASSID)
) IN USERSPACE1;

CREATE TABLE __DBSCHEMA__.SIBLISTING (
    ID INTEGER NOT NULL,
    SCHEMA_NAME VARCHAR(10),
    TABLE_NAME VARCHAR(10) NOT NULL,
    TABLE_TYPE CHAR(1) NOT NULL,
    PRIMARY KEY(ID)
) IN USERSPACE1;

CREATE TABLE __DBSCHEMA__.SIB000 (
    ID BIGINT NOT NULL,
    STREAM_ID BIGINT NOT NULL,
    TYPE CHAR(2),
    EXPIRY_TIME BIGINT,
    STRATEGY INTEGER,
    REFERENCE BIGINT,
    CLASS_ID INTEGER NOT NULL,
    PRIORITY INTEGER,
    SEQUENCE BIGINT,
    PERMANENT_ID INTEGER,
    TEMPORARY_ID INTEGER,
    LOCK_ID BIGINT,
    DATA_SIZE INTEGER NOT NULL,
    DATA VARCHAR(3360) FOR BIT DATA,
    LONG_DATA BLOB(1G),
    XID VARCHAR(254),
    DELETED SMALLINT,
    PRIMARY KEY(ID),
    REDELIVERED_COUNT INTEGER
) IN USERSPACE1;


CREATE INDEX __DBSCHEMA__.SIB000STREAMIX ON __DBSCHEMA__.SIB000(STREAM_ID,SEQUENCE) ALLOW REVERSE SCANS;

ALTER TABLE __DBSCHEMA__.SIB000 VOLATILE CARDINALITY;

CREATE TABLE __DBSCHEMA__.SIB001 (
    ID BIGINT NOT NULL,
    STREAM_ID BIGINT NOT NULL,
    TYPE CHAR(2),
    EXPIRY_TIME BIGINT,
    STRATEGY INTEGER,
    REFERENCE BIGINT,
    CLASS_ID INTEGER NOT NULL,
    PRIORITY INTEGER,
    SEQUENCE BIGINT,
    PERMANENT_ID INTEGER,
    TEMPORARY_ID INTEGER,
    LOCK_ID BIGINT,
    DATA_SIZE INTEGER NOT NULL,
    DATA VARCHAR(3360) FOR BIT DATA,
    LONG_DATA BLOB(1G),
    XID VARCHAR(254),
    DELETED SMALLINT,
    PRIMARY KEY(ID),
    REDELIVERED_COUNT INTEGER
) IN USERSPACE1;

CREATE INDEX __DBSCHEMA__.SIB001STREAMIX ON __DBSCHEMA__.SIB001(STREAM_ID,SEQUENCE) ALLOW REVERSE SCANS;

ALTER TABLE __DBSCHEMA__.SIB001 VOLATILE CARDINALITY;

CREATE TABLE __DBSCHEMA__.SIB002 (
    ID BIGINT NOT NULL,
    STREAM_ID BIGINT NOT NULL,
    TYPE CHAR(2),
    EXPIRY_TIME BIGINT,
    STRATEGY INTEGER,
    REFERENCE BIGINT,
    CLASS_ID INTEGER NOT NULL,
    PRIORITY INTEGER,
    SEQUENCE BIGINT,
    PERMANENT_ID INTEGER,
    TEMPORARY_ID INTEGER,
    LOCK_ID BIGINT,
    DATA_SIZE INTEGER NOT NULL,
    DATA VARCHAR(3360) FOR BIT DATA,
    LONG_DATA BLOB(1G),
    XID VARCHAR(254),
    DELETED SMALLINT,
    PRIMARY KEY(ID),
    REDELIVERED_COUNT INTEGER
) IN USERSPACE1;

CREATE INDEX __DBSCHEMA__.SIB002STREAMIX ON __DBSCHEMA__.SIB002(STREAM_ID,SEQUENCE) ALLOW REVERSE SCANS;

ALTER TABLE __DBSCHEMA__.SIB002 VOLATILE CARDINALITY;

CREATE TABLE __DBSCHEMA__.SIBXACTS (
    XID VARCHAR(254) NOT NULL,
    STATE CHAR(1) NOT NULL,
    PRIMARY KEY(XID)
) IN USERSPACE1;

CREATE TABLE __DBSCHEMA__.SIBKEYS (
    ID VARCHAR(50) NOT NULL,
    LAST_KEY BIGINT NOT NULL,
    PRIMARY KEY(ID)
) IN USERSPACE1;

GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNER TO USER __DBUSER__;
GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBOWNERO TO USER __DBUSER__;
GRANT SELECT,INSERT ON __DBSCHEMA__.SIBCLASSMAP TO USER __DBUSER__;
GRANT SELECT,INSERT ON __DBSCHEMA__.SIBLISTING TO USER __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB000 TO USER __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB001 TO USER __DBUSER__;
GRANT SELECT,INSERT,DELETE,UPDATE ON __DBSCHEMA__.SIB002 TO USER __DBUSER__;
GRANT SELECT,INSERT,UPDATE,DELETE ON __DBSCHEMA__.SIBXACTS TO USER __DBUSER__;
GRANT SELECT,INSERT,UPDATE ON __DBSCHEMA__.SIBKEYS TO USER __DBUSER__;
