-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2008 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

------------------------------------------------
SET CURRENT SCHEMA = '@WSRR_DB_SCHEMA@' ;

DROP INDEX @WSRR_DB_SCHEMA@.IDX_STMT_OBJ_HASH_REL;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_STMT_SUBJ_PRED_OBJ;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_STMT_PRED_OBJ_SUBJ;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_STMT_OBJ_SUBJ_PRED;

DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_PRED_OBJ_SUB;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_OBJ_SUBJ_PRED;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_INSTANCE_ROW;

DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_PRED;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_GRAPH;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_REL_OBJ;
DROP INDEX @WSRR_DB_SCHEMA@.IDX_GSTMT_REL_SUBJ;

DROP VIEW @WSRR_DB_SCHEMA@.SVC_STATEMENT;

DROP TABLE @WSRR_DB_SCHEMA@.GSTATEMENT;
DROP TABLESPACE @WSRR_DB_NAME@.GSTATMTS;

DROP TABLE @WSRR_DB_SCHEMA@.STATEMENT;
DROP TABLESPACE @WSRR_DB_NAME@.STATEMTS;


DROP TABLE @WSRR_DB_SCHEMA@.GRAPH;
DROP TABLESPACE @WSRR_DB_NAME@.GRAPHTS;

DROP INDEX @WSRR_DB_SCHEMA@.IDX_VALUE_LANG;
DROP TABLE @WSRR_DB_SCHEMA@.OBJECT;
DROP TABLESPACE @WSRR_DB_NAME@.OBJECTTS;
DROP TABLESPACE @WSRR_DB_NAME@.BLOAUXTS;

DROP TABLE @WSRR_DB_SCHEMA@.PREDICATE;
DROP TABLESPACE @WSRR_DB_NAME@.PREDICTS;

DROP TABLE @WSRR_DB_SCHEMA@.SUBJECT;
DROP TABLESPACE @WSRR_DB_NAME@.SUBJECTS;

DROP TABLE @WSRR_DB_SCHEMA@.MOD_LOCK;
DROP TABLESPACE @WSRR_DB_NAME@.WSRRTS15;

COMMIT;
