-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2006, 2009 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog

-- The WSRR installer will replace the DBNAME, DBUSER and DB2TSDIR variables in this file

-- CONNECT TO __DBNAME__;

-- Create Athene bufferpools and tablespaces
CREATE BUFFERPOOL ATHSTMTBP IMMEDIATE
    SIZE 65536 AUTOMATIC
    PAGESIZE 4K;
CREATE BUFFERPOOL ATHDATABP IMMEDIATE
    SIZE 16384 AUTOMATIC
    PAGESIZE 8K;
CREATE BUFFERPOOL ATHTEMPBP IMMEDIATE
    SIZE 2048 AUTOMATIC
    PAGESIZE 8K;
    
CREATE LARGE TABLESPACE ATHSTMTTS
    PAGESIZE 4K
    MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
    INITIALSIZE 80M
    INCREASESIZE 10 PERCENT
    MAXSIZE NONE
    EXTENTSIZE 16
    BUFFERPOOL ATHSTMTBP
    FILE SYSTEM CACHING;

CREATE LARGE TABLESPACE ATHDATATS
    PAGESIZE 8K
    MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
    INITIALSIZE 40M
    INCREASESIZE 10 PERCENT
    MAXSIZE NONE
    EXTENTSIZE 16
    BUFFERPOOL ATHDATABP
    FILE SYSTEM CACHING;
    
CREATE LARGE TABLESPACE ATHLOBTS
    PAGESIZE 32K
    MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
    INITIALSIZE 30M
    INCREASESIZE 10 PERCENT
    MAXSIZE NONE
    EXTENTSIZE 16
    FILE SYSTEM CACHING;

CREATE TEMPORARY TABLESPACE ATHTEMPTS
    PAGESIZE 8K
    MANAGED BY AUTOMATIC STORAGE
    BUFFERPOOL ATHTEMPBP;
-- begin_generated_IBM_copyright_prolog

-- Licensed Materials - Property of IBM
-- 
-- 5724-N72 5655-WBS
-- 
-- Copyright IBM Corp. 2012 All Rights Reserved.
-- 
-- US Government Users Restricted Rights - Use, duplication or
-- disclosure restricted by GSA ADP Schedule Contract with
-- IBM Corp.

-- end_generated_IBM_copyright_prolog


-- Create WSRR bufferpools and tablespaces
CREATE BUFFERPOOL WSRRBP IMMEDIATE
    SIZE 4096 AUTOMATIC
    PAGESIZE 32K;
CREATE BUFFERPOOL WSRRTMP IMMEDIATE
    SIZE 512 AUTOMATIC
    PAGESIZE 32K;
CREATE BUFFERPOOL WSRRUIBP IMMEDIATE
    SIZE 4096 AUTOMATIC
    PAGESIZE 32K;
    
CREATE LARGE TABLESPACE WSRRTS
    PAGESIZE 32K
    MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
    INITIALSIZE 50M
    INCREASESIZE 10 PERCENT
    MAXSIZE NONE
    EXTENTSIZE 16
    BUFFERPOOL WSRRBP
    FILE SYSTEM CACHING;

CREATE TEMPORARY TABLESPACE WSRRTEMP
    PAGESIZE 32K
    MANAGED BY AUTOMATIC STORAGE
    EXTENTSIZE 16
    BUFFERPOOL WSRRTMP
    FILE SYSTEM CACHING;

CREATE LARGE TABLESPACE WSRRUITS
    PAGESIZE 32K
    MANAGED BY AUTOMATIC STORAGE
    AUTORESIZE YES
    INITIALSIZE 50M
    INCREASESIZE 10 PERCENT
    MAXSIZE NONE
    EXTENTSIZE 16
    BUFFERPOOL WSRRUIBP
    FILE SYSTEM CACHING;    
-- DISCONNECT CURRENT ;
